spring:
  application:
    name: Foodish
  docker:
    compose:
      lifecycle-management: start_only
      file: ./compose.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5511/foodish
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: PostgreSQLDialect
server:
  port: 8081
