spring:
  application:
    name: Foodish
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/foodish
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: PostgreSQLDialect
